sudo: required
services:
  - docker

before_install:
  - docker build -t rayenrejeb/react-test-f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rayenrejeb/react-test npm run test -- --coverage

after_success:
  - docker build -t rayenrejeb/multi-client ./client
  - docker build -t rayenrejeb/multi-nginx ./nginx
  - docker build -t rayenrejeb/multi-server ./server
  - docker build -t rayenrejeb/multi-worker ./worker
  # Log In to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker HUB
  - docker push rayenrejeb/multi-client
  - docker push rayenrejeb/multi-nginx
  - docker push rayenrejeb/multi-server
  - docker push rayenrejeb/multi-worker
