version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - 3000:80
    restart: always
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDB=postgres
      - PGPWD=postgres_password
    depends_on:
      - postgres
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379